# Configuration file for Jekyll
# Site settings
title: Labin Ojha
description: My landing page
url: https://labinojha.com.np # Base URL for your GitHub Pages site
header_pages: [""]

# GitHub Pages specific settings
theme: minima
markdown: kramdown # Markdown parser to use
