# Configuration file for Jekyll
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
title: Labin Ojha
description: My landing page
url: https://labinojha.com.np # Base URL for your GitHub Pages site

# GitHub Pages specific settings
theme: pages-themes/primer@v0.2.0
markdown: kramdown # Markdown parser to use