# Configuration file for Jekyll

# Plugins
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Site settings
title: Labin Ojha
description: My landing page
url: https://labinojha.com.np # Base URL for your GitHub Pages site

# GitHub Pages specific settings
remote_theme: pages-themes/minimal@v0.2.0